### PR TITLE
add a code of conduct

### PR DESCRIPTION
**Pull request by kr**
Should have done this long, long ago.

### CODE REVIEW

**Comment by kr** [comment]
Hey folks. This project should have a code of conduct. The one at https://www.contributor-covenant.org/ seems pretty good.

Note that this isn't something I can just add a commit for on my own. We need project members to agree that it's a good thing, and it requires an ongoing commitment from people to enforce the rules. In particular, we need an email address to put in the document:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team at [INSERT EMAIL ADDRESS].

If we have consensus here, let's decide what email address to put in the document, and I'll update this PR and we can merge it!

cc @JensRantil @tomponline @ysmolsky

**Comment by ysmolsky** [comment]
Yes, this is something that is a must, so I vote for this step. As to email, I suggest, we setup google group (or another no-google alternative) where we invite all the members of the org. Its email address can be published in the code of conduct.

I see that we have this group: https://groups.google.com/forum/#!forum/beanstalk-talk, that is public, we could setup something like beanstalk-team that will be private.

**Comment by tomponline** [comment]
Yep I am happy with this too.

**Comment by ysmolsky** [comment]
Created a private group. Invited @JensRantil, @kr and @tomponline . We can use this email: groupbeanstalk-team@googlegroups.com

**Pull request merged**
