### PR TITLE
update protocol markdown format of chinese version

### PR DESCRIPTION
**Pull request by mickeyouyou**
for better adaptation of GitHub markdown format, update the file `doc/protocol.zh-CN.md`.

### CODE REVIEW

**Comment by mickeyouyou** [comment]
Can you merge the code?  @kr

**Comment by JensRantil** [comment]
Since the language of development is English, the Chinese documentation will constantly be outdated. I'm not sure this project should maintain a Chinese documentation.

**Comment by laixintao** [comment]
hi kr,

This pr only updated markdown style, so it can display better on GitHub, nothing else.

laixintao
www.kawabangga.com

**Comment by JensRantil** [comment]
There are merge conflicts. Please fix and resubmit.

**Comment by ysmolsky** [comment]
I do not see any fixes here. Closing. If you think that there should be fix, then please submit the changes and reopen.

**Pull request closed without merging**
