### PR TITLE
Build beanstalkd and run PHP Pheanstalk and Python Greenstalk testsuites against it

### PR DESCRIPTION
**Pull request by SamMousa**
This sets up a github action that:
- Builds beanstalkd on any push
- Runs the Pheanstalk test suite against the daemon

It's easily extensible to include other clients.
The idea behind this is that any push or PR confirms that clients won't break (or allows us to identify which clients break and thus give us an early warning for required downstream changes / fixes)

### CODE REVIEW

**Comment by SamMousa** [comment]
@tomponline sry for rudely pinging you, this PR and the other CI related one, all they do is add tests suites and automate the existing builds.
Anything you need me to elaborate on before you can consider these? 

Thanks for your reviews & merges yesterday!

**Comment by SamMousa** [comment]
How cool is this, your merge of the other bugfix already caused me to detect a failure in the greenstalk client!

https://github.com/SamMousa/beanstalkd/runs/4712188954?check_suite_focus=true

**Comment by SamMousa** [comment]
This PR just builds and runs test suites of some clients. Merging this does not affect Beanstalkd functionality but will allow us to find regressions or breaking changes early.

Any way we could get this merged?

**Comment by tomponline** [comment]
> 

Hi this seem sensible, I will try and find the time to review.

**Comment by SamMousa** [comment]
I can, will do tomorrow. Note that this PR just adds one file, you could just squash it since the history is not relevant.

**Comment by SamMousa** [comment]
Superseded by #630

**Pull request closed without merging**
