### PR TITLE
set up CI

### PR DESCRIPTION
**Pull request by SamMousa**
This configures a docker CI flow on pushes to master.
- The tests are run
- A container is built and pushed  to ghcr.io

This is already working on my fork, check it out here: https://github.com/SamMousa/beanstalkd/actions/runs/1638094865

### CODE REVIEW

**Comment by SamMousa** [comment]
Updated this to do only the 1 task: build & publish the beanstalkd container.

Running tests from beanstalkd clients is handled in a separate PR #614

**Comment by ysmolsky** [comment]
Thanks for looking in that. Does ghcr.io impose any limit on the amount of build? I see they have some size-limit, but what does it mean for us? I just want to make sure that we won't hit the limit very soon.

**Comment by SamMousa** [comment]
We won't. In general they are very generous for open source projects. So even if we were to get close to a limit they'd probably happily increase it for free.

**Comment by shadiramadan** [comment]
@ysmolsky anything blocking this...?

**Comment by ysmolsky** [comment]
@SamMousa I am sorry for delays on those. Do you think this PR is good in this current state?

**Review by ysmolsky — APPROVED** [review]

**Comment by SamMousa** [comment]
Yes I think it is! Thanks for merging!

**Comment by ssi-anik** [comment]
@SamMousa won't it be a good idea to mount a persistent volume so that the jobs don't get lost upon restart?

**Comment by SamMousa** [comment]
Yeah you probably want a bind mount for that. Using docker volumes isn't a very reliable way unless you have a very specific setup. but any distributed system you'll need a specific volume like a PVC in k8s. We don't need to have a volume defined in the Dockerfile for that

**Pull request merged**
