### PR TITLE
read from socket to the buffer instead of a char

### PR DESCRIPTION
**Pull request by ysmolsky**
~ % benchstat old.txt new.txt
name             old time/op    new time/op    delta
_put_delete_1k      318µs ± 3%     260µs ± 3%  -18.38%  (p=0.000 n=9+8)
_put_delete_64k     574µs ± 2%     514µs ± 8%  -10.49%  (p=0.000 n=10+10)
_put_delete_8       306µs ± 1%     256µs ± 2%  -16.51%  (p=0.000 n=8+9)
_put_delete_8k      365µs ± 3%     306µs ± 5%  -16.10%  (p=0.000 n=9+10)

name             old speed      new speed      delta
_put_delete_1k   4.83MB/s ± 0%  4.97MB/s ± 1%   +2.94%  (p=0.000 n=9+9)
_put_delete_64k   129MB/s ± 0%   148MB/s ±28%  +14.36%  (p=0.000 n=10+10)
_put_delete_8    40.0kB/s ± 0%  40.0kB/s ± 0%     ~     (all equal)
_put_delete_8k   28.4MB/s ±34%  38.9MB/s ± 1%  +36.76%  (p=0.000 n=10+10)

Updates #430

### CODE REVIEW

**Comment by ysmolsky** [comment]
It has improved the throughput just slightly...

**Comment by kr** [comment]
> It has improved the throughput just slightly...

Then I wonder if this change is worth the extra code… 🤔

**Comment by ysmolsky** [comment]
> > It has improved the throughput just slightly...
> 
> Then I wonder if this change is worth the extra code… 🤔

Same here. I have a suspicion that this code is not the slowest part of the benchmark (yet). So it's bottlenecked by something else. Also it might be that read is actually uses some kind of buffering already. On powerful Linux this code speeds up benchmarks up to 10%

**Comment by kr** [comment]
My understanding is that the kernel has network buffers for TCP connections and that, if those buffers don’t fill up, the throughout inprovement in this change comes from making fewer kernel calls, so fewer context switches.

But 10% is nothing to sneeze at.

**Comment by ysmolsky** [comment]
I have hacked a little ct.c to make it work with benchstat (https://github.com/kr/ct/issues/30)
and I got following:
```
~ % benchstat old.txt new.txt
name             old time/op    new time/op    delta
_put_delete_1k      318µs ± 3%     260µs ± 3%  -18.38%  (p=0.000 n=9+8)
_put_delete_64k     574µs ± 2%     514µs ± 8%  -10.49%  (p=0.000 n=10+10)
_put_delete_8       306µs ± 1%     256µs ± 2%  -16.51%  (p=0.000 n=8+9)
_put_delete_8k      365µs ± 3%     306µs ± 5%  -16.10%  (p=0.000 n=9+10)

name             old speed      new speed      delta
_put_delete_1k   4.83MB/s ± 0%  4.97MB/s ± 1%   +2.94%  (p=0.000 n=9+9)
_put_delete_64k   129MB/s ± 0%   148MB/s ±28%  +14.36%  (p=0.000 n=10+10)
_put_delete_8    40.0kB/s ± 0%  40.0kB/s ± 0%     ~     (all equal)
_put_delete_8k   28.4MB/s ±34%  38.9MB/s ± 1%  +36.76%  (p=0.000 n=10+10)
```

**Comment by kr** [comment]
That is interesting! But those *p* values suggest the results might not be super reliable haha. It might need a higher repetition count?

**Comment by ysmolsky** [comment]
I thought that low or next to zero values of `p` are good, no? 
I have not ran it many times, n=10 there. 

I tried to run the same benchmark with n=50 and what I got. There are peaks of slowness in 64k benchmarks 
```
Benchmarkput_delete_64k     3000            490953 ns/op         187.73 MB/s
Benchmarkput_delete_64k     3000            488790 ns/op         187.84 MB/s
Benchmarkput_delete_64k     3000            462030 ns/op         189.30 MB/s
Benchmarkput_delete_64k     3000           1764607 ns/op          39.09 MB/s
Benchmarkput_delete_64k     3000            629254 ns/op         180.57 MB/s
Benchmarkput_delete_64k     3000            532570 ns/op         185.52 MB/s
Benchmarkput_delete_64k     1000           1190625 ns/op          64.31 MB/s
Benchmarkput_delete_64k     3000            723916 ns/op          97.47 MB/s
Benchmarkput_delete_64k     3000            550059 ns/op         184.60 MB/s
Benchmarkput_delete_64k     3000            741290 ns/op          97.21 MB/s
Benchmarkput_delete_64k     3000            529147 ns/op         185.70 MB/s
Benchmarkput_delete_64k     3000            535995 ns/op         185.34 MB/s
```
and multiple errors in 8k size:
```
start server port=51635 pid=48825
>1025 put 0 0 0 8192
>1025 a ...SKIP... a>1025
<1025 select: Invalid argument
error (exit status 1)
Benchmarkput_delete_8k
```
It happens both in master and this branch. I guess the high value of FD might be related, maybe FDs are not closed soon enough.

**Comment by ysmolsky** [comment]
I have found a workaround for this bug and run cttest multiple times from the shell:
```
make ct/_ctcheck ; repeat 25 { ct/_ctcheck -test . -bench 'ctbench_put_*' } > new.txt```
Results for n=25:
```
name            old time/op    new time/op    delta
put_delete_1k      314µs ± 3%     260µs ± 5%  -17.23%  (p=0.000 n=24+23)
put_delete_64k     530µs ± 3%     478µs ± 4%   -9.69%  (p=0.000 n=21+23)
put_delete_8       311µs ± 3%     255µs ± 2%  -17.96%  (p=0.000 n=24+24)
put_delete_8k      360µs ± 2%     307µs ± 3%  -14.62%  (p=0.000 n=25+24)

name            old speed      new speed      delta
put_delete_1k   4.84MB/s ± 0%  4.97MB/s ± 1%   +2.59%  (p=0.000 n=23+23)
put_delete_64k   186MB/s ± 0%   188MB/s ± 1%   +1.48%  (p=0.000 n=21+23)
put_delete_8    40.0kB/s ± 0%  40.0kB/s ± 0%     ~     (all equal)
put_delete_8k   37.9MB/s ± 0%  38.9MB/s ± 0%   +2.48%  (p=0.000 n=24+24)
```
Even though time/op has dropped > 10%, the speed has increased  < 3%

**Comment by kr** [comment]
> I thought that low or next to zero values of p are good, no?

Ah yes, of course you are right. Sorry about that!

**Pull request closed without merging**
